# Data Preprocessing

### Importing the dataset
```{r}
dataset = read.csv('Data.csv')
print("The raw dataset: ")
print(dataset)
```


### Taking care of missing data
```{r}
dataset$Age = ifelse(is.na(dataset$Age),
                     ave(dataset$Age, FUN = function(x) mean(x, na.rm = TRUE)),
                     dataset$Age)
dataset$Salary = ifelse(is.na(dataset$Salary),
                        ave(dataset$Salary, FUN = function(x) mean(x, na.rm = TRUE)),
                        dataset$Salary)
print("The dataset after taking care of missing data:")
print(dataset)
```


### Encoding categorical data
```{r}
dataset$Country = factor(dataset$Country,
                         levels = c('France', 'Spain', 'Germany'),
                         labels = c(1, 2, 3))
dataset$Purchased = factor(dataset$Purchased,
                           levels = c('No', 'Yes'),
                           labels = c(0, 1))
print("The dataset after taking care of missing data and encoding categorical data:")
print(dataset)
```
